// ^
// Property of Luka Vukmirica - All Rights Reserved. (luka.vukmirica@gmail.com)

// Generates src/tanh_table.h: the Q15 tanh lookup table plus TANH_SHIFT, the shift the
// firmware uses to turn a reservoir accumulator (ACC) into a table row.
//
// Build + run (from the tactic/ folder):
//   cc -std=c11 -Wall -Wextra -Wconversion host/tanh_lut_gen.c -o build/tanh_lut_gen -lm
//   ./build/tanh_lut_gen > src/tanh_table.h
//
// Only the header text goes to stdout (that is what > saves). Errors go to stderr.

#include <stdio.h> // For input/output
#include <stdint.h> // For integer values
#include <inttypes.h> // For PRId32 (portable int32_t printing)
#include <math.h> // For math libraries

#define N 256 // 256 steps along the desired inteval of tanh (or other activation)
#define DOMAIN_R 4 // The [-4 to 4] interval of values (The domain radius)
#define Q15_ONE 32767 // Integer 1 of fixed point
#define RES_SHIFT 16 // Q format of kernels
#define GAIN 4 // Gain scale for activation (Should be power of two to avoid multiplying on uC)

#define PER_LINE 8 // Table values printed per line



int main(void){
    double step = (2.0*DOMAIN_R)/N;

    // ---- TANH_SHIFT: the firmware's rule for ACC -> table row ----
    // row = (ACC >> TANH_SHIFT) + N/2
    // ACC is Q16 (divide by 2^RES_SHIFT), times GAIN, times rows per unit of x.
    // All three are powers of two, so together they collapse into one right shift.

    // 1. Rows per unit of x must be a whole number
    if (N % (2*DOMAIN_R) != 0){
        fprintf(stderr, "ERROR: N (%d) is not divisible by 2*DOMAIN_R (%d)\n", N, 2*DOMAIN_R);
        return 1;
    }
    int32_t rows_per_unit = N / (2*DOMAIN_R); // 256 / 8 = 32

    // 2. Total scale from real ACC value to rows
    int32_t m = GAIN * rows_per_unit; // 4 * 32 = 128

    // 3. m must be a power of two (exactly one bit set) or no single shift can do it
    if (m <= 0 || (m & (m - 1)) != 0){
        fprintf(stderr, "ERROR: GAIN * N/(2*DOMAIN_R) = %" PRId32 " is not a power of two\n", m);
        return 1;
    }

    // 4. log2(m): count shifts until m reaches 1
    int32_t bits = 0;
    while (m > 1){
        m >>= 1;
        bits++;
    } // 128 -> 7

    // 5. Remove those bits from the kernel's Q format
    int32_t tanh_shift = RES_SHIFT - bits; // 16 - 7 = 9
    if (tanh_shift <= 0){
        fprintf(stderr, "ERROR: TANH_SHIFT = %" PRId32 " (must be > 0); GAIN too large for RES_SHIFT\n", tanh_shift);
        return 1;
    }

    // ---- Top of the header ----
    printf("// ^\n");
    printf("// Property of Luka Vukmirica - All Rights Reserved. (luka.vukmirica@gmail.com)\n");
    printf("/* GENERATED by host/tanh_lut_gen.c -- do not edit.\n");
    printf("   Regenerate: ./build/tanh_lut_gen > src/tanh_table.h\n");
    printf("   Params: N=%d DOMAIN_R=%d Q15_ONE=%d RES_SHIFT=%d GAIN=%d\n", N, DOMAIN_R, Q15_ONE, RES_SHIFT, GAIN);
    printf("   Row i holds tanh(-DOMAIN_R + i*2*DOMAIN_R/N) in Q15; row N/2 is x = 0.\n");
    printf("   Firmware lookup: row = ((ACC + (1 << (TANH_SHIFT-1))) >> TANH_SHIFT) + N/2, clamped to [0, N-1]. */\n");
    printf("#ifndef TANH_TABLE_H\n");
    printf("#define TANH_TABLE_H\n\n");
    printf("#include <stdint.h>\n\n");
    printf("#define TANH_N      %d\n", N);
    printf("#define TANH_SHIFT  %" PRId32 "\n\n", tanh_shift);
    printf("static const int16_t TANH_LUT[TANH_N] = {\n");

    // ---- The table ----
    for (int32_t i = 0; i < N; i++){
        double val = -DOMAIN_R + (i*step);
        double out = tanh(val)*Q15_ONE;
        int32_t outint = (int32_t)round(out);

        // Must fit in the int16_t the firmware stores it in
        if (outint < INT16_MIN || outint > INT16_MAX){
            fprintf(stderr, "ERROR: row %" PRId32 " = %" PRId32 " does not fit in int16_t\n", i, outint);
            return 1;
        }

        if (i % PER_LINE == 0){
            printf("    "); // Indent at the start of each line
        }

        printf("%6" PRId32 "%s", outint, (i == N - 1) ? "  " : ", ");// No comma after the last value

        if (i % PER_LINE == PER_LINE - 1){
            printf("  /* %3" PRId32 " */\n", i - (PER_LINE - 1)); // Index of the first value on this line
        }
    }

    // ---- Bottom of the header ----
    printf("};\n\n");
    printf("#endif\n");

    return 0;
}
